# 선형 대수

## 행렬

### 스칼라

In [1]:
# 1. 스칼라의 정의: 크기를 가진 물리량
#       표현식: a = 1
#       사칙 연산은 기존과 같음
# 2. 벡터의 정의: 크기와 방향을 가진 물리량
#       표현식: a = [2, 3], b = [2, 4, 5]
def AddVector ():
    w = []
    u = [3, 2, 12]
    c = [4, 1, 19]

    len(u)

    if len(u) != len(c):
        return F"덧셈 불가능: {len(u)}, {len(c)}"

    for i in range (0, len(u)):
        w.append(u[i] + c[i])

    return w

# 넘파이 사칙 연산 실습
import numpy as np
def numpy_v_test ():
    u = np.array([4, 24, 29])
    v = np.array([42, 402, 210])

    w = u + v
    print("numpy + :", w)

    w = u - v
    print("numpy - :", w)

    w = 2 * u
    print("numpy s* :", w)

    w = u * v
    print("numpy * :", w)

    w = u / v
    print("numpy / :", w)

print(AddVector())
print(numpy_v_test())

[7, 3, 31]
numpy + : [ 46 426 239]
numpy - : [ -38 -378 -181]
numpy s* : [ 8 48 58]
numpy * : [ 168 9648 6090]
numpy / : [0.0952381  0.05970149 0.13809524]
None


In [5]:
X = [ [3, 2, 1], [2, 7, -1], [4, 0, -1] ]
y = [5 ,1, 3]

x0 = X[0]
x1 = X[1]
x2 = X[2]

y0 = y[0]
y1 = y[1]
y2 = y[2]

print("원본 행렬")
print(x0, y0)
print(x1, y1)
print(x2, y2)


원본 행렬
[3, 2, 1] 5
[2, 7, -1] 1
[4, 0, -1] 3


In [10]:
tmp = 1/x0[0] # 1행 1열의 원소를 1로 만들기 위한 변수값
print(tmp)

# 1행 1열의 원소를 1로 만듬
x0 = [ ele * tmp for ele in x0 ]
y0 = y0 * tmp
print(x0)
print(y0)

# 2행을 1로 만들기
x0_tmp = [ ele * -x1[0] for ele in x0 ]
y0_tmp = y0 * -x1[0]
print(x0_tmp)
print(y0_tmp)

for i in range(0, len(x0)):
    x1[i] = x0_tmp[i] + x1[i]

y1 = y0_tmp + y1
print("수정본 1")
print(x0, y0)
print(x1, y1)
print(x2, y2)


1.0
[1.0, 0.6666666666666666, 0.3333333333333333]
1.6666666666666665
[-0.0, -0.0, -0.0]
-0.0
수정본 1
[1.0, 0.6666666666666666, 0.3333333333333333] 1.6666666666666665
[0.0, 5.666666666666667, -1.6666666666666665] -2.333333333333333
[4, 0, -1] 3


In [13]:
# 3행의 4를 0으로 만들기
x1_tmp = [ ele * -x2[0] for ele in x0 ]
y0_tmp = y1 * -x2[0]
print(x1_tmp)
print(y0_tmp)

for i in range(0, len(x0)):
    x2[i] = x1_tmp[i] + x2[i]

y2 = y0_tmp + y2

[-4.0, -2.6666666666666665, -1.3333333333333333]
9.333333333333332


In [14]:


import numpy as np

r = np.array([ [1, 2, 3] ])
print (r.shape)

(1, 3)


In [42]:
a = np.zeros((2, 2))
print (a)

b = np.ones((2, 2))
print (b)

c = np.full((2, 2), 7)
print (c)

d = np.random.random((2, 2))
print(d)
d.T

[[0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]]
[[7 7]
 [7 7]]
[[0.09828544 0.71434529]
 [0.15690031 0.32775827]]


array([[0.09828544, 0.15690031],
       [0.71434529, 0.32775827]])

In [38]:
A = np.array([ [1, 2], [3, 4], [5, 6] ])
print(A)
A.T

[[1 2]
 [3 4]
 [5 6]]


array([[1, 3, 5],
       [2, 4, 6]])

In [36]:
B = np.array([ [5, 6], [7, 8], [9, 10] ])
B

array([[ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [41]:
# 행렬의 곱
np.dot(B, A)

ValueError: shapes (3,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)

In [75]:
# 방정식
A = np.random.random((3, 3))
B = np.random.random((3, 4))
C = np.dot(A, B)
print(C.T)

y = np.random.random((3, 1))
y

[[0.37874993 0.58732804 0.33332628]
 [0.67879263 1.17252091 0.90477261]
 [0.82453549 1.31825545 0.90011509]
 [0.62599156 0.92777947 0.51729927]]


array([[0.15646601],
       [0.00182317],
       [0.46081261]])

In [76]:
# I
eye4 = np.eye(4)
print(eye4)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [77]:
# 역행렬
from numpy.linalg import inv
A_inv = inv(A)
A_inv

array([[-13.13430532,  13.39849279,  -6.49087473],
       [-14.07698787,  11.34816037,  -3.12525434],
       [ 36.56736897, -30.46347762,  12.16240492]])

In [78]:
# 행렬의 원소 곱
A * A_inv

array([[ -5.09237119,   4.21952496,  -1.86833692],
       [ -7.2569198 ,   7.97552269,  -1.42422563],
       [  4.59015361, -24.78133751,   4.35709563]])

In [79]:
# 행렬의 곱
A.dot(A_inv)

array([[ 1.00000000e+00,  0.00000000e+00, -4.44089210e-16],
       [ 0.00000000e+00,  1.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00, -1.77635684e-15,  1.00000000e+00]])

In [80]:
x = A_inv.dot(B)
x

array([[ -5.77139805,  -0.43397128, -11.87843575, -15.80751064],
       [ -7.01870523,  -2.83580814, -10.75492925, -13.72128224],
       [ 17.99309278,   6.88958802,  31.20773732,  39.26184459]])

In [81]:
# 해 구하기
from numpy.linalg import solve
x = solve(A, C)
x

array([[0.73111413, 0.92177761, 0.99040101, 0.85115744],
       [0.29170519, 0.92295515, 0.53970959, 0.09982278],
       [0.01188308, 0.10680696, 0.94001222, 0.91907856]])