In [9]:
import numpy as np

x = np.array([
    [ 1, 2 ],
    [ 3, 4 ]
])

print(x)

[[1 2]
 [3 4]]


In [12]:
y = np.random.random(size=(3,3))
print(y)

[[0.91204189 0.88575845 0.7828931 ]
 [0.09507645 0.37256486 0.52566803]
 [0.23792459 0.32769537 0.68555421]]


## 파이썬 문법

In [95]:
# 기본 연산
a = 1 + 2
b = 1 - 2
c = 1 * 2
d = 1 / 2
e = 1 % 2
f = 1 ** 2
print(F'a: {a}')
print(F'b: {b}')
print(F'c: {c}')
print(F'd: {d}')
print(F'e: {e}')
print(F'f: {f}')

a: 3
b: -1
c: 2
d: 0.5
e: 1
f: 1


In [19]:
# 문자열 정의
a = "fdsfs"
b = '"Isn\'t," they said.'
print(a, b)

fdsfs "Isn't," they said.


In [92]:
a = "Test"
print(a[0])
print(a[-1])

T
t


In [28]:
a = "1234567"
print(a[:3])
print(a[-2:])
len(a)

123
67


7

In [34]:
def makeTest (n):
    matrix = []
    for col in range (0, n):
        row = []
        for raw in range (0, n):
            if col == raw:
                row.append(n)
            else:
                row.append(0)
        matrix.append(row)
    return matrix

print(makeTest(5))

[[5, 0, 0, 0, 0], [0, 5, 0, 0, 0], [0, 0, 5, 0, 0], [0, 0, 0, 5, 0], [0, 0, 0, 0, 5]]


In [35]:
a = []
for x in range(0, 10):
    if x == 5:
        pass
    else:
        a.append(x)

print(a)

[0, 1, 2, 3, 4, 6, 7, 8, 9]


In [40]:
def a ():
    arr = []

    # 디폴트 파라미터
    def x (b = 10):
        b = b + 1
        return b

    print("x =", x())

print(a())

x = 11
None


In [55]:
b = "fdsafas"

def a (str, *args, **keywords):
    print("첫번쨰 매계변수 :", str)

    print("-" * 20)
    print("추가 args")
    for arg in args:
        print(arg)

    print("** 키워드 인자")
    print(keywords)
    for key in keywords:
        print(key, ":", keywords[key])

    return

print(a("a", "b", "c",
        넌뭐니="Michael Palin",
        client="John Cleese",
        sketch="Cheese Shop Sketch"))

첫번쨰 매계변수 : a
--------------------
추가 args
b
c
** 키워드 인자
{'넌뭐니': 'Michael Palin', 'client': 'John Cleese', 'sketch': 'Cheese Shop Sketch'}
넌뭐니 : Michael Palin
client : John Cleese
sketch : Cheese Shop Sketch
None


In [57]:
for i, v in enumerate(['1', '2', '3']):
    print(i, v)

0 1
1 2
2 3


In [87]:
questions = ['name', 'quest', 'favorite color']
answers = ['lancelot', 'the holy grail', 'blue']
dc = ['33333', '444444', '55555']

for i, (q, a, d) in enumerate(zip(questions, answers, dc)):
    print(F'{questions[i]} - {answers[i]} - {dc[i]}')


name - lancelot - 33333
quest - the holy grail - 444444
favorite color - blue - 55555


In [ ]:
dict(a=1, b=2, c=3)

['a', 'b', 'c', 'd']
['a', 'b', 'c', 'd']
d
deque(['a', 'b', 'c', 'd'])
a


In [ ]:
a = ["a", "b", "c"]
a.append("d")
print(a)
b = a.copy().pop()
print(a)
print(b)

from collections import deque
Q = deque(a)
d = Q.copy().popleft()
print(Q)
print(d)


###
