# Python & DataSpell Tutorial

In [9]:
import numpy as np

x = np.array([
    [ 1, 2 ],
    [ 3, 4 ]
])

print(x)

[[1 2]
 [3 4]]


In [12]:
y = np.random.random(size=(3,3))
print(y)

[[0.91204189 0.88575845 0.7828931 ]
 [0.09507645 0.37256486 0.52566803]
 [0.23792459 0.32769537 0.68555421]]


## 파이썬 문법

In [13]:
# 기본 연산
a = 1 + 1
b = 1 - 1
c = 1 * 1
d = 1 / 1
e = 1 % 1
f = 1 ** 1

In [19]:
# 문자열 정의
a = "fdsfs"
b = '"Isn\'t," they said.'
print(a, b)

fdsfs "Isn't," they said.


In [21]:
a = "fefpwfwe"
print(a[0])
print(a[-1])

f
e


In [28]:
a = "1234567"
print(a[:3])
print(a[-2:])
len(a)

123
67


7

In [34]:
def makeTest (n):
    matrix = []
    for col in range (0, n):
        row = []
        for raw in range (0, n):
            if col == raw:
                row.append(n)
            else:
                row.append(0)
        matrix.append(row)
    return matrix

print(makeTest(5))

[[5, 0, 0, 0, 0], [0, 5, 0, 0, 0], [0, 0, 5, 0, 0], [0, 0, 0, 5, 0], [0, 0, 0, 0, 5]]


In [35]:
a = []
for x in range(0, 10):
    if x == 5:
        pass
    else:
        a.append(x)

print(a)

[0, 1, 2, 3, 4, 6, 7, 8, 9]


In [40]:
def a ():
    arr = []

    # 디폴트 파라미터
    def x (b = 10):
        b = b + 1
        return b

    print("x =", x())

print(a())

x = 11
None


In [49]:
b = "fdsafas"

def a (str, *args, **keywords):
    print("첫번쨰 매계변수 :", str)
    print("//" * 20)

    for arg in args:
        print(arg)

    for key in keywords:
        print(key, ":", keywords[key])

    return



print(a("a", "b", "c",
        넌뭐니="Michael Palin",
        client="John Cleese",
        sketch="Cheese Shop Sketch"))

첫번쨰 매계변수 : a
////////////////////////////////////////
b
c
넌뭐니 : Michael Palin
client : John Cleese
sketch : Cheese Shop Sketch
None
