#### 역행렬 실습
##### 역행렬은 행렬식과 수반행렬이 필요하다

In [13]:
import numpy as np

A = [[2, 1, 3],
     [4, 2, 1],
     [5, 9, 1]]

## 영행렬 생성 함수
def zero_mat(n, p):
    """
    영 행렬 생성
    :param n:
    :param p:
    :return: n x p 영행렬 Z
    """
    Z = []
    for i in range(0, n):
        row = []
        for j in range(0, p):
            row.append(0)
        Z.append(row)
    return Z

## 행렬 깊은 복사 함수
def deepcopy(A):
    """
    깊은 복사 -> A 행렬의 스칼라 값을 그대로 복사
    :param A:
    :return: A의 깊은 복사가 완료된 행렬 리스트 res
    """
    if (type(A[0])) == list:
        n = len(A)
        p = len(A[0])
        res = zero_mat(n, p)

        for i in range(0, n):
            for j in range(0, p):
                res[i][j] = A[i][j]

        return res
    else:
        n = len(A)
        res = []

        for i in range(0, n):
            res.append(A[i])

        return res

## 행렬식 함수
def det_mat(A):
    n = len(A)
    p = len(A[0])
    detA = 0

    for j in range(0, p):
        M = [ A[1][:j] + A[1][j + 1:], A[2][:j] + A[2][j + 1:] ]
        Mij = M[0][0] * M[1][1] + M[0][1] * M[1][0] # aij의 행렬식
        Cij = ( (-1) ** (0 + j) ) * Mij # aij에 대한 여인수

        detA += A[0][j] * Cij # 행렬식

    return detA

## 행렬식 생성 함수
def det_rec(A):
    """
    행렬 A의 행렬식을 구하는 함수
    :param A:
    :return: 행렬 A의 행렬식 res
    """

    n = len(A)
    p = len(A[0])
    res = 0

    ## 2x2 행렬인 경우
    if n == 2:
        res = A[0][0] * A[1][1] + A[1][0] * A[0][1]
        return res

    ## nxn 행렬
    for i in range(0, n): ## 원본 행렬 X의 모든 row를 방문
        X = deepcopy(A) ## 깊은 복사로 입력 행렬 A를 복사
        X = X[1:] ## 1행을 제외한 나머지 행렬
        nx = len(X) ## 가져온 X의 row 개수

        for j in range(0, nx): ## X 행렬의 모든 row를 방문
            X[j] = X[j][0:i] + X[j][i + 1:] ## X 행렬의 j번쨰 row의 원소 중 0 ~ i이전, i + 1 ~ 마지막

        sign = (-1) ** (i % 2)
        sub_det = det_rec(X)
        res += sign * A[0][i] * sub_det

    return res

## 넘파이 행렬식 함수
def det_mat_np(A):
    return np.linalg.det(A)

## 여인수 행렬 생성 함수
def C_mat(A):
    n = len(A) # A행렬의 row
    C = [] # 여인수 함수 베이스

    for i in range(0, n): # A행렬의 각 row 방문
        row_C = [] # 여인수 행렬 C의 row 생성 베이스 생성
        idx_r = list(range(0, n)) # A행렬의 row의 idx를 요소로 하는 배열 생성
        idx_r.remove(i) # 방문한 row 인덱스 삭제

        for j in range(0, n): # j = 모든 row의 인덱스 방문
            idx_c = list(range(0, n)) # 여인수의 인덱스를 요소로 하는 배열 생성
            idx_c.remove(j) # 여인수의 row 중 방문한 인덱스 삭제

            M = [] # 부분 행렬 생성

            for k in idx_r: # 방문 한 row를 제거한 인덱스를 방문, k = 방문하지 않은 row의 A 행렬 인덱스
                row_M = [] # 행렬식 row
                for l in idx_c: # 여인수의 행렬식
                    val = A[k][l]
                    row_M.append(val)
                M.append(row_M)

            Mij = det_rec(M) ## aij에 대한 소행렬식
            Cij = ( (-1) ** (i + j) ) * Mij # aij에 대한 여인수
            row_C.append(Cij) # aij에 대한 여인수를 여인수 행렬에 추가
        C.append(row_C)

    ## 생성된 여인수 함수 리턴
    return C

## 여인수 행렬
print(C_mat(A))

[[11, -9, 46], [-28, 17, -23], [7, -14, 8]]


#### 수반 행렬
##### 여인수 행렬의 전치 행렬

In [14]:
C = C_mat(A) # A행렬의 여인수 행렬 생성 함수
def transpose(A):
    """
    전치 행렬 생성 함수
    :param A:
    :return:
    """

    n = len(A)
    p = len(A[0])
    At = []

    for row in range(0, p):
        t_row = []

        for col in range(0, n):
            t_row.append(A[col][row])

        At.append(t_row)

    return At

adjA = transpose(C_mat(A))
print(adjA)

[[11, -28, 7], [-9, 17, -14], [46, -23, 8]]


In [15]:
## 넘파이
import numpy as np
A = np.array(A)
invA = np.linalg.inv(A)
print(A)
print("-----------")
print(invA)

[[2 1 3]
 [4 2 1]
 [5 9 1]]
-----------
[[-0.10769231  0.4        -0.07692308]
 [ 0.01538462 -0.2         0.15384615]
 [ 0.4        -0.2         0.        ]]
